import { StyleSheet } from 'react-native';
import { theme } from '@/src/theme';

export const styles = StyleSheet.create({
  card: {
    backgroundColor: theme.colors.white,
    borderRadius: theme.radius.xl,
    marginBottom: theme.spacing.lg,
    shadowColor: theme.colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 6,
    overflow: 'hidden',
  },
  cardContent: {
    flexDirection: 'row',
    padding: theme.spacing.xl,
  },
  imageContainer: {
    position: 'relative',
    marginRight: theme.spacing.lg,
  },
  image: {
    width: 80,
    height: 80,
    borderRadius: theme.radius.lg,
    backgroundColor: theme.colors.gray100,
  },
  imageOverlay: {
    position: 'absolute',
    bottom: -8,
    right: -8,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: theme.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: theme.colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  content: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: theme.spacing.lg,
  },
  titleContainer: {
    flex: 1,
  },
  title: {
    fontSize: theme.fontSizes.xl,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.gray800,
    marginBottom: theme.spacing.sm,
    letterSpacing: -0.2,
  },
  statusBadge: {
    backgroundColor: theme.colors.green50,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: theme.spacing.xs,
    borderRadius: theme.radius.md,
    alignSelf: 'flex-start',
  },
  statusText: {
    fontSize: theme.fontSizes.xs,
    color: theme.colors.green600,
    fontWeight: theme.fontWeight.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  deleteButton: {
    padding: theme.spacing.sm,
    borderRadius: theme.radius.base,
    backgroundColor: theme.colors.red50,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: theme.spacing.md,
  },
  iconContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: theme.colors.gray50,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: theme.spacing.md,
  },
  infoText: {
    fontSize: theme.fontSizes.base,
    color: theme.colors.gray500,
    fontWeight: theme.fontWeight.medium,
    flex: 1,
  },
  textPreview: {
    backgroundColor: theme.colors.gray50,
    borderRadius: theme.radius.base,
    padding: theme.spacing.md,
    marginTop: theme.spacing.sm,
    borderWidth: 1,
    borderColor: theme.colors.gray200,
  },
  previewText: {
    fontSize: theme.fontSizes.sm,
    color: theme.colors.gray500,
    lineHeight: 18,
    fontWeight: theme.fontWeight.medium,
  },
  // Modal de imagem expandida
  imageWrapper: {
    position: 'relative',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: theme.colors.blackStrong,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalBackground: {
    flex: 1,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    padding: theme.spacing.xl,
  },
  modalBackgroundTouchable: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingBottom: 80,
  },
  modalContent: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  closeButton: {
    position: 'absolute',
    top: 50,
    right: 20,
    zIndex: 2,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    borderRadius: 20,
    padding: theme.spacing.sm,
  },
  expandedImage: {
    width: '100%',
    height: '80%',
    borderRadius: theme.radius.base,
  },
  expandedImageContainer: {
    width: '100%',
    height: '80%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalInfo: {
    position: 'absolute',
    bottom: 80,
    left: 20,
    right: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    padding: theme.spacing.lg,
    borderRadius: theme.radius.base,
    alignItems: 'center',
  },
  modalTitle: {
    color: theme.colors.white,
    fontSize: theme.fontSizes.xl,
    fontWeight: theme.fontWeight.bold,
    marginBottom: theme.spacing.xs,
  },
  modalSubtitle: {
    color: theme.colors.white,
    fontSize: theme.fontSizes.base,
    opacity: 0.8,
  },
  modalInstructions: {
    color: theme.colors.white,
    fontSize: theme.fontSizes.sm,
    opacity: 0.6,
    marginTop: theme.spacing.sm,
    textAlign: 'center',
    fontStyle: 'italic',
  },
});
